services:
  backend:
    build:
      context: .
      dockerfile: package/backend/Dockerfile
    container_name: projet-web-backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000

  frontend:
    build:
      context: .
      dockerfile: package/frontend/Dockerfile
    container_name: projet-web-frontend
    ports:
      - "4173:4173"
    environment:
      NODE_ENV: production
      # À utiliser côté front : import.meta.env.VITE_API_BASE_URL
      VITE_API_BASE_URL: http://localhost:3000
    depends_on:
      - backend
